Book entity, repository and service layers add
jszymanski97/online-book-store-app pull request #1
Opened 2024-08-25 13:19 UTC by jszymanski97

Book entity created
BookRepository and impl created
BookService and impl created
application.properties modified to connect db
BookStoreApp functions tested

2024-08-25 16:46 UTC, beatarjn requested changes

2024-08-25 16:46 UTC, beatarjn commented on src/main/java/mate/project/repository/BookRepositoryImpl.java
> +
Pls remove empty line

2024-08-25 16:46 UTC, beatarjn commented on src/main/java/mate/project/OnlineBookStoreAppApplication.java
> +                Book book = new Book();
Book creation could be extracted to a separate private method for better readability

2024-08-25 16:46 UTC, beatarjn commented on src/main/java/mate/project/service/BookServiceImpl.java
> +
Pls don't start class with an empty line

2024-08-25 16:46 UTC, beatarjn commented on src/main/java/mate/project/service/BookServiceImpl.java
> +    @Autowired
Constructor injection is generally preferred because it enforces the dependency requirement at the time of object creation and it's easier to test. You can use also @AllArgsConstructor annotation

2024-08-26 14:49 UTC, MateuszRostek approved these changes

2024-08-26 14:49 UTC, MateuszRostek commented on src/main/java/mate/project/OnlineBookStoreAppApplication.java
>                  book.setIsbn("isbn");
It should all be in the `createBook` method.

2024-09-01 07:54 UTC, MateuszRostek reviewed
I've approved this Pull Requesst last week, you should only make one change that I've suggested and then you should merge this branch to the`main`. Then you should create a new branch and provide solution for the next task there. At the end, you should create another Pull Request (do not push changes into the same one).

2024-09-01 10:27 UTC, jszymanski97 commented
@MateuszRostek  right... I see I din't quite get what to do with the next task but now it makes sense... I will revert my previous commit and push the changes to the main. Than crerate new pull request with the new task and also the suggested change from previus one

2024-09-01 10:55 UTC, merged