BookController and dto implemented
jszymanski97/online-book-store-app pull request #2
Opened 2024-09-01 11:02 UTC by jszymanski97

BookController.java - created with supporting BookDto.java and CreateBookRequestDto.java classes
MapperConfig.java - implemented mapstruct to ease the class conversion
EntityNotFoundException.java - exception created for error message clarity

2024-09-01 15:21 UTC, MateuszRostek requested changes
Nice try! See some advice and implement required changes.

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/dto/BookDto.java
> +
Do not add redundant empty spaces.

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/dto/CreateBookRequestDto.java
> +
Do not add redundant empty spaces.

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/dto/CreateBookRequestDto.java
> +}
Make it a `record`.

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/mapper/BookMapper.java
> +
Do not add redundant empty spaces.

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/repository/BookRepository.java
> +    Book getBookById(Long id);
You should use Optional here:
```suggestion
    Optional<Book> getBookById(Long id);
```

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/service/BookServiceImpl.java
> +
Do not add redundant empty spaces.

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/java/mate/project/service/BookServiceImpl.java
> +        return bookMapper.toBookDto(savedModel);
```suggestion
        return bookMapper.toBookDto(bookRepository.save(model));
```

2024-09-01 15:21 UTC, MateuszRostek commented on src/main/resources/application.properties
Add this one also:

`spring.jpa.open-in-view=false`

2024-09-01 17:12 UTC, jszymanski97 commented on src/main/java/mate/project/repository/BookRepository.java
> +    Book getBookById(Long id);
Okay, I went by the video where the coach explained to use optional for methods like findBookById where we not sure if the book exists, and for methods with get we dont need to. But I see and understand why it is better to use optional for both cases

2024-09-02 16:13 UTC, MateuszRostek commented
In general I do not recommend to use and create methods of type `get`, it is safer to create methods of type `find` and return Optional from them:)

2024-09-02 16:14 UTC, MateuszRostek approved these changes
Good job!

2024-09-02 16:14 UTC, MateuszRostek commented
Remember to merge this branch and create solution on the new one with new pull request:)

2024-09-02 16:16 UTC, merged